stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project"

test_job:
  stage: test
  script:
    - echo "Running tests"
  needs: ["build_job"]  # Test job runs only after build_job completes successfully

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project"
  needs: ["test_job"]  # Deploy job runs only after test_job completes successfully
